[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TopLynx"
authors = [{name = "UselessTechJunks", email = "useless.tech.junks@gmail.com"}]
dynamic = ["version", "description"]
